Writing ops agent fields with structured logs
GoogleCloudPlatform/ops-agent pull request #1253
Opened 2023-05-15 17:49 UTC by rafaelwestphal

## Description

## Related issue

## How has this been tested?

## Checklist:
- Unit tests
  - [ ] Unit tests do not apply.
  - [ ] Unit tests have been added/modified and passed for this PR.
- Integration tests
  - [ ] Integration tests do not apply.
  - [ ] Integration tests have been added/modified and passed for this PR.
- Documentation
  - [ ] This PR introduces no user visible changes.
  - [ ] This PR introduces user visible changes and the corresponding documentation change has been made.
- Minor version bump
  - [ ] This PR introduces no new features.
  - [ ] This PR introduces new features, and there is a separate PR to bump the [minor version](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/VERSION) since the last [release](https://github.com/GoogleCloudPlatform/ops-agent/releases) already.
  - [ ] This PR bumps the version.

2023-05-16 21:10 UTC, jefferbrecht requested changes

2023-05-17 14:32 UTC, franciscovalentecastro commented on confgenerator/confgenerator.go
> +				"Regex": "ops-agent-version ^\\d.*",
Does this `FILTER` with the `Regex` pattern match is checking the `plain text` json or the parsed json for a field `ops-agent-version` ?

2023-05-17 14:57 UTC, rafaelwestphal commented on confgenerator/confgenerator.go
> +	return "${logs_dir}/../health-checks.log"
Will do as a follow up as discussed offline. It will require changes in a bunch of places and the PR will get a bit too big.

2023-05-17 15:02 UTC, jefferbrecht commented on confgenerator/confgenerator.go
> +				"Regex": "ops-agent-version ^.*",
Nit: the `^` isn't needed either.

2023-05-17 15:02 UTC, jefferbrecht approved these changes

2023-05-17 15:06 UTC, franciscovalentecastro commented on confgenerator/confgenerator.go
> +	return "${logs_dir}/../health-checks.log"
Some comments :
- I think using `path.Join` is a simple change to do.
- I agree this feels brittle. AFAIU, the `{logs_dir}` path with `......./subagents` comes from the systemd configuration [1], but this is running in the `..._engine.service` (which uses the default path) not on the `..._fluent-bit.service` so I'm confused.


[1] https://github.com/GoogleCloudPlatform/ops-agent/blob/f9a08d67b47bc5b9e7f55e8364da02068fd85746/systemd/google-cloud-ops-agent-fluent-bit.service.d/directories.conf

2023-05-17 18:25 UTC, merged

2023-05-18 16:01 UTC, rafaelwestphal commented on confgenerator/confgenerator.go
> +	return "${logs_dir}/../health-checks.log"
Created b/283253077 to track this internal cleanup