Redis logging documentation
GoogleCloudPlatform/ops-agent pull request #233
Opened 2021-10-07 01:02 UTC by dehaansa

Add documentation for redis logging receiver, this was missed in the original PR.

2021-10-07 03:20 UTC, qingling128 approved these changes

2021-10-07 03:20 UTC, qingling128 commented on docs/redis.md
> +          - redis
```suggestion
        - redis
```

2021-10-11 22:42 UTC, quentinmit requested changes

2021-10-11 22:42 UTC, quentinmit commented on docs/redis.md
> +        - redis
This should be redis_default since that's what you named the receiver above

2021-10-12 20:59 UTC, merged