Reject redundant entries in supported_applications.txt
GoogleCloudPlatform/ops-agent pull request #438
Opened 2022-03-01 21:48 UTC by martijnvans

Raise a test failure if the same application appears more than once in supported_applications.txt. This is to prevent the situation that https://github.com/GoogleCloudPlatform/ops-agent/pull/432 is fixing from reoccurring.

Needs https://github.com/GoogleCloudPlatform/ops-agent/pull/432 to be merged, otherwise this will obviously fail.

2022-03-01 23:06 UTC, igorpeshansky requested changes

2022-03-01 23:06 UTC, igorpeshansky commented on integration_test/third_party_apps_test.go
> +			return fmt.Errorf("application %q appears multiple times in supported_applications.txt", app)
[Optional] Would it make sense to list all duplicates?

2022-03-01 23:06 UTC, igorpeshansky commented on integration_test/third_party_apps_test.go
> +	unique := make(map[string]bool)
The name `unique` implies that it would be true for items that are unique, and false for duplicates. Would `seen` be a better name?

2022-03-04 17:33 UTC, igorpeshansky approved these changes
LGTM :shipit:

2022-03-04 17:33 UTC, igorpeshansky commented on integration_test/third_party_apps_test.go
> +			return fmt.Errorf("application %q appears multiple times in supported_applications.txt", app)
I guess by resolving this you were saying that reporting one duplicate at a time is fine. Well, it was optional anyway. For the record, I was suggesting something like:
```
func rejectDuplicates(apps []string) error {
	seen := make(map[string]bool)
	var dups []string
	for _, app := range apps {
		if seen[app] {
			dups = append(dups, app)
		}
		seen[app] = true
	}
	if len(dups) > 0 {
		return fmt.Errorf("applications %q appear multiple times in supported_applications.txt", dups)
	}
	return nil
}
```

2022-03-08 17:45 UTC, martijnvans commented
yes, I both think that reporting one duplicate at a time is fine and that the code for reporting all duplicates is more complex and not worth it. So I'll go ahead and proceed with the current approach.

2022-03-10 21:18 UTC, merged